todo_app/urls.py
from django.urls import path
from . import views

app_name = "todo_app"

urlpatterns = [
    path('', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('home/<str:uid>', views.home, name='home'),
    path('add/<str:uid>', views.add_task, name='add'),
    path('del/<str:id>/<str:uid>', views.delete, name='del'),
    path('views_task/<str:id>/<str:uid>', views.views_task, name='views_task'),
    path('edit/<str:id>/<str:uid>', views.edit_task, name='edit'),
    path('view_add_status/<str:uid>', views.add_status, name='add_status'),
    path('view_status/<str:uid>', views.home_status, name='home_status'),
    path('view_status_edit/<str:id>/<str:uid>/<str:stat>', views.task_status_edit, name='task_status_edit'),
    path('view_status_del/<str:id>/<str:stat>/<str:uid>', views.task_status_del, name='task_status_del'),
    path('filter_values/<str:flt>/<str:uid>', views.filter_hours, name='filter'),
    path('filter_values_tasks/<str:flt>/<str:uid>', views.filter_task, name='filter_task'),

]

todo_proj/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todo_app.urls'))
]

todo_app/models.py
from db_connect import db


# Connect to MongoDB
db = db
db_list = db['todo_list']
db_register = db['todo_register']
db_status =  db['todo_status']

todo_app/views.py
from bson import ObjectId
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import db_list, db_register, db_status, db
from datetime import datetime, timedelta
from functools import wraps
from django.http import HttpRequest


def get_cookie(cookie_name):

    def decorator(view_func):
        @wraps(view_func)
        def wrapper(request, *args, **kwargs):
            if isinstance(request, HttpRequest):
                cookie_value = request.COOKIES.get(cookie_name)
                data = db.uid.find_one({'uid':ObjectId(cookie_value)})
                if data is None:
                    messages.error(request,"Please Login, found to be not registered ")
                    return redirect('todo_app:login')
                else:
                    return view_func(request, *args, **kwargs)

        return wrapper

    return decorator




def register(request):
    if request.method == "POST":
        storage = {'email': request.POST.get("email"), 'name': request.POST.get("name"),
                   'password': request.POST.get("password"), 'user_creation_time': datetime.now()}
        db_register.insert_one(storage)
        messages.success(request, "You Have Been Registered Successfully!")
        return redirect('todo_app:login')
    else:
        return render(request, 'todo_app/register.html')


def login(request):
    if request.method == "POST":
        cred = {'email': request.POST.get('email'), 'password': request.POST.get('password')}
        find_db = db_register.find_one({'email': cred['email']})
        if find_db is None:
            messages.error(request, "There Was An Error Logging In, Please Try Again...")
            return redirect('todo_app:login')
        elif find_db['password'] == cred['password']:
            messages.success(request, "You Have Been Logged In!")
            uid = find_db['_id']
            # Set cookie
            response = redirect('todo_app:home', uid=uid)
            response.set_cookie('uid', uid,
                                expires=datetime.now() + timedelta(days=30))  # Set cookie expiration as required
            db.uid.insert_one({'uid': uid, 'logintime': datetime.now()})

            return response
        else:
            messages.error(request, "Your given Credentials doesn't match")
            return redirect('todo_app:login')

    return render(request, 'todo_app/login.html')


@get_cookie('uid')
def home(request, uid):
    if uid:
        user_cred = db_register.find_one({'_id': ObjectId(uid)})
        user_id = uid
        user_name = user_cred['name']
        data_task = db_list.find({'user_id': ObjectId(user_id)})
        data_status = db_status.find(({'user_id': ObjectId(user_id)}))
        task_list = list(data_task)
        task_status = list(data_status)
        for i in task_list:
            i.update({"task_id": i['_id']})
            i.pop("_id")
        return render(request, 'todo_app/home.html',
                      {'task_list': task_list, 'task_status': task_status, 'uid': uid, 'uname': user_name})
    else:
        return redirect('todo_app:login')

@get_cookie('uid')
def add_task(request, uid):
    if uid:
        if request.method == "POST":
            storage = {'task_title': request.POST.get('task_title'), 'task_desc': request.POST.get('task_desc'),
                       'task_comm': request.POST.get('task_comm'), 'task_status': request.POST.get('task_status'),
                       'creation_task_time': datetime.now(), 'user_id': ObjectId(uid)}
            db_list.insert_one(storage)
            messages.success(request, "Your Data has been added Successfully")
            return redirect('todo_app:home', uid=uid)
        user_cred = db_register.find_one({'_id': ObjectId(uid)})
        user_name = user_cred['name']
        opt_list = db_status.find({'user_id': ObjectId(uid)})
        uid = uid
        return render(request, 'todo_app/add_task.html', {'opt_list': opt_list, 'uid': uid, 'uname': user_name})
    else:
        return redirect('todo_app:login')

@get_cookie('uid')
def edit_task(request, id, uid):
    if uid:
        if request.method == "POST":
            storage = {'task_title': request.POST.get('task_title'), 'task_desc': request.POST.get('task_desc'),
                       'task_comm': request.POST.get('task_comm'), 'task_status': request.POST.get('task_status'),
                       'updated_task_time ': datetime.now()}
            db_list.update_one({"_id": ObjectId(id)}, {"$set": storage})
            messages.success(request, "Yor data hase been updated")
            return redirect('todo_app:home', uid=uid)
        user_cred = db_register.find_one({'_id': ObjectId(uid)})
        opt_list = db_status.find({'user_id': ObjectId(uid)})
        f_data = db_list.find_one({"_id": ObjectId(id)})
        user_name = user_cred['name']
        obj = id
        uid = uid
        return render(request, 'todo_app/edit_task.html',
                      {'data': f_data, 'opt_list': opt_list, 'obj': obj, 'uid': uid, 'uname': user_name})
    else:
        return redirect('todo_app:login')

@get_cookie('uid')
def delete(request, id, uid):
    if uid:
        uid = uid
        db_list.delete_one({"_id": ObjectId(id)})
        messages.success(request, "Your Task Has Been Deleted")
        return redirect('todo_app:home', uid=uid)
    else:
        return redirect('todo_app:login')

@get_cookie('uid')
def views_task(request, id, uid):
    if uid:
        data = db_list.find_one({"_id": ObjectId(id)})
        user_cred = db_register.find_one({'_id': ObjectId(uid)})
        user_name = user_cred['name']
        uid = uid
        obj = id
        data.update({"task_id": str(data['_id'])})
        data.pop("_id")
        return render(request, 'todo_app/views_task.html', {'data': data, 'obj': obj, 'uid': uid, 'uname': user_name})
    else:
        return redirect('todo_app:login')

@get_cookie('uid')
def home_status(request, uid):
    if uid:
        data_status = db_status.find({'user_id': ObjectId(uid)})
        user_cred = db_register.find_one({'_id': ObjectId(uid)})
        user_name = user_cred['name']
        data_s_list = list(data_status)
        for i in data_s_list:
            i.update({"task_id": i['_id']})
            i.pop("_id")
        return render(request, 'todo_app/view_stat_home.html',
                      {'data_s_list': data_s_list, 'uid': uid, 'uname': user_name})
    else:
        return redirect('todo_app:login')

@get_cookie('uid')
def add_status(request, uid):
    if uid:
        user_cred = db_register.find_one({'_id': ObjectId(uid)})
        user_name = user_cred['name']
        if request.method == "POST":
            storage = {'t_status': request.POST.get('t_status'), 'user_id': ObjectId(uid),
                       'task_creation_time': datetime.now(), 'user_name': user_name}
            db_status.insert_one(storage)
            messages.success(request, "Your task has been added successfully")
            return redirect('todo_app:home', uid=uid)

        return render(request, 'todo_app/add_status.html', {'uid': uid, 'uname': user_name})
    else:
        return redirect('todo_app:login')

@get_cookie('uid')
def task_status_del(request, id, stat, uid):
    if uid:
        db_status.delete_one({"_id": ObjectId(id)})
        db_list.delete_many({"task_status": stat})
        messages.success(request, "Your Status  Has Been Deleted")
        uid = uid
        return redirect('todo_app:home_status', uid=uid)
    else:
        return redirect('todo_app:login')

@get_cookie('uid')
def task_status_edit(request, id, uid, stat):
    if uid:
        user_cred = db_register.find_one({'_id': ObjectId(uid)})
        user_name = user_cred['name']
        if request.method == "POST":
            storage = {'t_status': request.POST.get('t_status'), 'user_id': user_cred['_id'],
                       'task_update_time': datetime.now()}
            db_status.update_one({"_id": ObjectId(id)}, {'$set': storage})
            db_list.update_many({'task_status': stat}, {'$set': {"task_status": storage['t_status']}})
            messages.success(request, "Yor data hase been updated")
            return redirect('todo_app:home', uid=uid)
        data = db_status.find_one({"_id": ObjectId(id)})
        stat = data['t_status']
        kid = data['_id']
        return render(request, 'todo_app/task_status_edit.html',
                      {'data': data, 'uid': user_cred['_id'], 'uname': user_name, 'kid': kid, 'stat': stat})
    else:
        return redirect('todo_app:login')

@get_cookie('uid')
def filter_hours(request, flt, uid):
    if uid:
        if flt == "LastH":
            time = datetime.now()
            delta = timedelta(hours=1)
            t_time = time - delta
            stime = "1 Hour"
        elif flt == "Last2H":
            time = datetime.now()
            delta = timedelta(hours=2)
            t_time = time - delta
            stime = "2 Hour"
        elif flt == "Last3H":
            time = datetime.now()
            delta = timedelta(hours=3)
            t_time = time - delta
            stime = "3 Hour"
        elif flt == "Last12H":
            time = datetime.now()
            delta = timedelta(hours=12)
            t_time = time - delta
            stime = "12 Hour"
        elif flt == "Last24H":
            time = datetime.now()
            delta = timedelta(hours=24)
            t_time = time - delta
            stime = "24 Hour"
        data_task = db_list.find({"creation_task_time": {"$gte": t_time, "$lte": time}})
        data_status = db_status.find(({'user_id': ObjectId(uid)}))
        user_cred = db_register.find_one({'_id': ObjectId(uid)})
        user_name = user_cred['name']
        task_list = list(data_task)
        task_status = list(data_status)
        for i in task_list:
            i.update({"task_id": i['_id']})
            i.pop("_id")
        return render(request, 'todo_app/filter_home.html',

todo_app/templates/todo_app/add_status.html
{% extends 'todo_app/base.html' %}

{% block content %}

<div class="container">
    <br><h2>Add status </h2> <br>
    <form method="POST" action="{% url 'todo_app:add_status' uid=uid%}" class="form-container">
        {% csrf_token %}
        <div class="form-group">

            <label for="id_t_status">T status:</label>

            <input type="text" class="form-control" name="t_status" required="" id="id_t_status"> <br>

            <button type="submit" class="btn btn-primary">Submit</button>

        </div>
    </form> <br>

    <input type="button" class="btn btn-primary"  value="Back" onclick="goBack()">

</div>
{% endblock%}

todo_app/templates/todo_app/add_task.html
{% extends 'todo_app/base.html' %}
{% block content %}
<div class="container">
    <form action="{% url 'todo_app:add' uid=uid %}" class="form-container" method="POST">
        <br><h1>Add Task </h1> <br>
        {% csrf_token %}


        <div class="form-group">
            <label for="id_task_title">Task title:</label>
            <input type="text" class="form-control" name="task_title" required="" id="id_task_title">
        </div>


        <div class="form-group">
            <label for="id_task_desc">Task desc:</label>
            <input type="text" class="form-control" name="task_desc" required="" id="id_task_desc">
        </div>


        <div class="form-group">
            <label for="id_task_comm">Task comm:</label>
            <textarea class="form-control" name="task_comm" required="" id="id_task_comm"></textarea>
        </div>

        <div class="form-group">
            <label for="id_task_status">Task status:</label>
            <select class="form-control" name="task_status" id="id_task_status">
                {% for i in opt_list %}
                <option value="{{i.t_status}}">{{i.t_status}}</option>
                {{% endfor %}
            </select>
        </div>

        <br>
        <button type="submit" class="btn btn-primary">Add</button>

        <a href="{% url 'todo_app:home' uid=uid %}">
            <button type="button" class="btn btn-secondary">Back</button>
        </a>
    </form>
</div>
{% endblock %}

todo_app/templates/todo_app/edit_task.html
{% extends 'todo_app/base.html' %}
{% block content %}
<div class="container">
    <form action="{% url 'todo_app:edit' id=obj uid=uid %}" class="form-container" method="POST">
        {% csrf_token %}
        <br> <h1>Update Task </h1> <br>
        <div class="form-group">
            <label>Title</label> <input class="form-control" type="text" name="task_title" value="{{data.task_title}}"> <br>

            <label>Task Descripation</label> <input class="form-control" type="text" name="task_desc}" value="{{data.task_desc}}"> <br>

            <label>Task Comment</label> <textarea class="form-control" name="task_comm" value="{{data.task_comm}}" rows="4"> </textarea> <br>
        </div>

        <div class="form-group">
            <label>Task Status</label>
            <select class="form-control " name="task_status" id="data_task_status">
                {% for i in opt_list %}
                <option value="{{i.t_status}}">{{i.t_status}}</option>
                {{% endfor %}
            </select> <br>
        </div>

        <button type="submit" class="btn btn-primary">Update Data</button>

        <a href="{% url 'todo_app:home' uid=uid %}">
            <button type="button" class="btn btn-secondary">Back</button>
        </a>
    </form>
</div>

{% endblock %}

todo_app/templates/todo_app/filter_home.html
{% extends 'todo_app/base.html' %}
{% block content %}

<div class="container">
<br>
<br><h1>Filtered by {{time}}</h1> <br>
<div class="container">
  <div class="row">
    <div class="col dropdown  ">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                        Filter by Task Status
                    </button>
                    <ul class="dropdown-menu">
                        {% for m in task_status %}
                        <li><a class="dropdown-item" href="{% url 'todo_app:filter_task' flt=m uid=uid %}">{{m.t_status}}</a></li>
                        {% endfor %}
                    </ul>

    </div>
    <div class="col dropdown  ">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                        Filter by timeslot
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'todo_app:filter' flt='LastH' uid=uid %}">Last Hour</a></li>
                        <li><a class="dropdown-item" href="{% url 'todo_app:filter' flt='Last2H' uid=uid %}">Last Two hours</a></li>
                        <li><a class="dropdown-item" href="{% url 'todo_app:filter' flt='Last3H' uid=uid %}">Last Three hours </a></li>
                        <li><a class="dropdown-item" href="{% url 'todo_app:filter' flt='Last12H' uid=uid %}">Last 12 hours </a></li>
                        <li><a class="dropdown-item" href="{% url 'todo_app:filter' flt='Last24H' uid=uid%}">Last 24 hours </a></li
                    </ul>

    </div>
 </div>
</div>
<br>
{% for j in task_status %}
<table class="table    table-striped table-hover ">
    <thead class="table-dark">
    <tr>
        <th scope="col" colspan="5">

            <h1 class="text">
                {{j.t_status}}
            </h1>

        </th>
    </tr>
    </thead>
    <thead class="table-light">
    <tr>
        <th scope="col">Sr. No.</th>
        <th scope="col">Task title</th>
        <th scope="col">Task Description</th>
        <th scope="col">            </th>
    </tr>
    </thead>
    <tbody>
    {% for i in task_list %}
    {% if j.t_status == i.task_status %}
    <tr>
        <td scope="row">{{ forloop.counter }}</td>
        <td> {{i.task_title}}</td>
        <td> {{i.task_desc}}</td>
        <td>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                    Action
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'todo_app:views_task' id=i.task_id uid=uid %}">Detail</a></li>
                    <li><a class="dropdown-item" href="{% url 'todo_app:edit' id=i.task_id uid=uid %}">Edit</a></li>
                    <li><a class="dropdown-item" href="{% url 'todo_app:del' id=i.task_id uid=uid %}">Delete</a></li>
                </ul>
            </div>
        </td>


    </tr>
    {% endif %}
    {% endfor %}
    </tbody>
</table>
{% endfor %}

 <center><a href="{% url 'todo_app:home' uid=uid %}">
            <button type="button" class="btn btn-secondary">Back</button>
        </a> </center>
</div>
{% endblock %}

todo_app/templates/todo_app/filter_task.html
{% extends 'todo_app/base.html' %}
{% block content %}
<div class="container">
    <br>
    <br><h1>Filtered by {{task_name.t_status}} status</h1> <br>
    <div class="container">
      <div class="row">

        <div class="col dropdown  ">

                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                            Filter by Task Status
                        </button>
                        <ul class="dropdown-menu">
                            {% for m in task_status %}
                            <li><a class="dropdown-item" href="{% url 'todo_app:filter_task' flt=m.t_status uid=uid %}">{{m.t_status }}</a></li>
                            {% endfor %}
                        </ul>

        </div>
        <div class="col dropdown  ">

                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                            Filter by timeslot
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'todo_app:filter' flt='LastH' uid=uid %}">Last Hour</a></li>
                            <li><a class="dropdown-item" href="{% url 'todo_app:filter' flt='Last2H' uid=uid %}">Last Two hours</a></li>
                            <li><a class="dropdown-item" href="{% url 'todo_app:filter' flt='Last3H' uid=uid %}">Last Three hours </a></li>
                            <li><a class="dropdown-item" href="{% url 'todo_app:filter' flt='Last12H' uid=uid %}">Last 12 hours </a></li>
                            <li><a class="dropdown-item" href="{% url 'todo_app:filter' flt='Last24H' uid=uid %}">Last 24 hours </a></li
                        </ul>

        </div>
     </div>
    </div>
    <br>
    <table class="table    table-striped table-hover ">
        <thead class="table-dark">

        <tr>
            <th scope="col">Sr. No.</th>
            <th scope="col">Task title</th>
            <th scope="col">Task Desc</th>
            <th scope="col">Task Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for i in task_list %}
        <tr>
            <td scope="row">{{ forloop.counter }}</td>
            <td> {{i.task_title}}</td>
            <td> {{i.task_desc}}</td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                        Action
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'todo_app:views_task' id=i.task_id uid=uid %}">Detail</a></li>
                        <li><a class="dropdown-item" href="{% url 'todo_app:edit' id=i.task_id uid=uid %}">Edit</a></li>
                        <li><a class="dropdown-item" href="{% url 'todo_app:del' id=i.task_id uid=uid%}">Delete</a></li>
                    </ul>
                </div>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
      <center><a href="{% url 'todo_app:home' uid=uid %}">
                <button type="button" class="btn btn-secondary">Back</button>
      </a></center>
</div>
{% endblock %}

todo_app/templates/todo_app/home.html
{% extends 'todo_app/base.html' %}
{% block content %}
<br>
<div class="container">
  <div class="row">

    <div class="col dropdown  ">

                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                        Filter by Task Status
                    </button>
                    <ul class="dropdown-menu">
                        {% for m in task_status %}
                        <li><a class="dropdown-item" href="{% url 'todo_app:filter_task' flt=m.t_status uid=uid %}">{{m.t_status}}</a></li>
                        {% endfor %}
                    </ul>

    </div>
    <div class="col dropdown  ">

                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                        Filter by timeslot
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'todo_app:filter' flt='LastH' uid=uid %}">Last Hour</a></li>
                        <li><a class="dropdown-item" href="{% url 'todo_app:filter' flt='Last2H' uid=uid %}">Last Two hours</a></li>
                        <li><a class="dropdown-item" href="{% url 'todo_app:filter' flt='Last3H' uid=uid %}">Last Three hours </a></li>
                        <li><a class="dropdown-item" href="{% url 'todo_app:filter' flt='Last12H' uid=uid %}">Last 12 hours </a></li>
                        <li><a class="dropdown-item" href="{% url 'todo_app:filter' flt='Last24H' uid=uid %}">Last 24 hours </a></li
                    </ul>

    </div>
 </div>

<br>

{% for j in task_status %}
<table class="table    table-striped table-hover ">
    <thead class="table-dark">
    <tr>
        <th scope="col" colspan="5">

            <h1 class="text">
                {{j.t_status}}
            </h1>

        </th>
    </tr>
    </thead>
    <thead class="table-light">
    <tr>
        <th scope="col">Sr. No.</th>
        <th scope="col">Task title</th>
        <th scope="col">Task Description</th>
        <th scope="col">            </th>
    </tr>
    </thead>
    <tbody>
    {% for i in task_list %}
    {% if j.t_status == i.task_status %}
    <tr>
        <td scope="row">{{ forloop.counter }}</td>
        <td> {{i.task_title}}</td>
        <td> {{i.task_desc}}</td>
        <td>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                    Action
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'todo_app:views_task' id=i.task_id uid=uid %}">Detail</a></li>
                    <li><a class="dropdown-item" href="{% url 'todo_app:edit' id=i.task_id uid=uid %}">Edit</a></li>
                    <li><a class="dropdown-item" href="{% url 'todo_app:del' id=i.task_id uid=uid %}">Delete</a></li>
                </ul>
            </div>
        </td>


    </tr>
    {% endif %}
    {% endfor %}
    </tbody>
</table>
{% endfor %}
</div>
{% endblock %}

todo_app/templates/todo_app/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="nav-link active" aria-current="page" href="{% url 'todo_app:home' uid=uid %}">Home</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'todo_app:add' uid=uid  %}">Add task</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'todo_app:add_status' uid=uid  %}">Add status</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'todo_app:home_status' uid=uid  %}">Working
                        status</a>
                </li>

            </ul>

            <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Welcome {{uname}},</a>
            </div>

            <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                <a class="nav-link active" aria-current="page" href="{% url 'todo_app:login' %}">
                    <button type="button" class="btn btn-danger">Logout</button></a>
            </div>


        </div>
    </div>
</nav>

todo_app/templates/todo_app/task_status_edit.html
{% extends 'todo_app/base.html' %}
{% block content %}
<div class="container">
    <form action="{% url 'todo_app:task_status_edit' id=kid stat=stat uid=uid %}" class="form-container" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <br>
        <h1>Update Status </h1> <br>
        <label>Edit Task </label> <input type="text" class="form-control" name="t_status" value="{{data.t_status}}">
        <br><br>

        <button type="submit" class="btn btn-primary">Update Data</button>
        <a href="{% url 'todo_app:home_status' uid=uid %}">
            <button type="button" class="btn btn-secondary">Back</button>
        </a>

    </div>
    </form>
</div>


{% endblock %}

todo_app/templates/todo_app/view_stat_home.html
{% extends 'todo_app/base.html' %}
{% block content %}
<br>
<div class="container">
    <table class="table table-striped table-hover table-bordered">
        <thead class="table-dark">
        <tr>
            <th>Sr. No.</th>
            <th>Types of Status</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for i in data_s_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ i.t_status }}</td>
            <td>
                <a href="{% url 'todo_app:task_status_edit' id=i.task_id stat=i.t_status  uid=uid %}">
                    <button type="button" class="btn btn-success">Edit</button>
                </a>
                <a href="{% url 'todo_app:task_status_del'  id=i.task_id  stat=i.t_status  uid=uid %}">
                    <button type="button" class="btn btn-danger">Delete</button>
                </a>
            </td>

        </tr>
        {% endfor %}
        </tbody>

    </table>
            <center><a href="{% url 'todo_app:home' uid=uid %}"> <button type="button" class="btn btn-lg btn-primary">Home</button>
            </a></center>
</div>
{% endblock %}

todo_app/templates/todo_app/views_task.html
{% extends 'todo_app/base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="container p-5 my-5 bg-dark text-white">
        <div class="lh-1">
            <h1 >Detail View Task  </h1>
        </div>
      </div>
    <div class="container p-5 my-5 align-items-center  rounded shadow-sm">
        <div class="lh-1">
            {% for i,j in data.items %}
             <h4>
             <label>{{i}} :</label> {{ j }}
            </h4>
            {% endfor %}
        </div>
      </div>
    <div class="container p-5 my-5 align-items-center  bg-dark-grey rounded shadow-sm">
        <div class="lh-1">
            <a href="{% url 'todo_app:edit' id=obj uid=uid %}">
                <button type="submit" class="btn btn-secondary">Edit </button>
            </a>

            <a href="{% url 'todo_app:del' id=obj uid=uid %}">
                <button type="submit" class="btn btn-warning"> Delete </button>
            </a>

            <a href="{% url 'todo_app:home' uid=uid %}">
                <button type="submit" class="btn btn-info"> Back </button>
            </a>
        </div>
    </div>
</div>
{% endblock %}